#!/usr/bin/env bash
#
# build-overhead-test-set.sh — assemble a regression test set for the
# overhead piano alignment detector, in ~/Pictures/pianocam-sim/test-set/.
#
# The set mixes:
#   1. A clean synthetic-piano baseline (best-case)
#   2. 10 frames from a Synthesia-style Chopin tutorial video (~/Downloads/),
#      sampled across the performance — clean intro, mid-play with hand
#      occlusion, end of track. Real overhead, real lighting.
#   3. Two CC-licensed Wikimedia photos — extreme close-up and oblique
#      near-overhead — as harder edge cases.
#
# Run with the cycling launcher to step through and read alignment stats:
#   tools/build-overhead-test-set.sh
#   tools/run-with-sim-overhead.sh ~/Pictures/pianocam-sim/test-set

set -euo pipefail
cd "$(dirname "$0")/.."

DIR="$HOME/Pictures/pianocam-sim/test-set"
WORK="$(mktemp -d)"
trap "rm -rf $WORK" EXIT

mkdir -p "$DIR"
rm -f "$DIR"/*.jpg

# --- 1. Synthetic baseline ----------------------------------------------------
# Generated by tools/render-synthetic-piano.py with a small rotation so the
# black-key centers vary in both x and y (otherwise the homography matrix is
# rank-deficient — same root cause we fixed in PianoKeyboardAlignmentDetector).
if [[ -f "$HOME/Pictures/pianocam-sim/synthetic_piano_rot.jpg" ]]; then
  cp "$HOME/Pictures/pianocam-sim/synthetic_piano_rot.jpg" "$DIR/00-synthetic-rotated.jpg"
else
  echo "warning: synthetic baseline not found at ~/Pictures/pianocam-sim/synthetic_piano_rot.jpg" >&2
fi

# --- 2. Chopin tutorial frames ------------------------------------------------
CHOPIN="$HOME/Downloads/YTDown_YouTube_Chopin-Waltz-in-A-minor-B-150-Op-Posth_Media_eN5z1mu6j4M_001_1080p — PianoCam.mp4"
if [[ -f "$CHOPIN" ]]; then
  # Top 720px of the 1920x1080 frame == the real overhead piano region
  # (the bottom band is PianoCam's synthetic 88-key composite, which we don't want).
  for ts in 0 15 30 45 60 75 100 120 150 160; do
    label="$(printf '%02d-chopin-t%d.jpg' $((10#${ts}<16 ? 1 : 99)) "$ts")"
    # Use a simple sequential numbering so the directory cycles in order:
    :
  done
  # Sequential numbering (separate loop for clarity)
  i=1
  for ts in 0 15 30 45 60 75 100 120 150 160; do
    out="$(printf '%s/%02d-chopin-t%d.jpg' "$DIR" "$i" "$ts")"
    ffmpeg -y -ss "$ts" -i "$CHOPIN" -frames:v 1 -vf "crop=1920:720:0:0" -q:v 2 "$out" 2>/dev/null
    i=$((i + 1))
  done
else
  echo "warning: Chopin source video not found at $CHOPIN" >&2
fi

# --- 3. Wikimedia photos (CC BY-SA) -------------------------------------------
# https://commons.wikimedia.org/wiki/File:Pianotoetsen.jpg  — extreme close-up
# https://commons.wikimedia.org/wiki/File:Piano_Keys.JPG    — oblique close-up
curl -sSL -o "$DIR/11-wikimedia-pianotoetsen-closeup.jpg" \
  "https://upload.wikimedia.org/wikipedia/commons/a/ad/Pianotoetsen.jpg"
curl -sSL -o "$DIR/12-wikimedia-piano-keys-oblique.jpg" \
  "https://upload.wikimedia.org/wikipedia/commons/d/de/Piano_Keys.JPG"

echo
echo "Test set written to: $DIR"
ls -la "$DIR/"
